CREATE TABLE `wbs_face_device` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`type` varchar(10) NOT NULL COMMENT '设备类型 wx微信  ali支付宝',
	`status` tinyint(1) DEFAULT NULL,
	`device_number` varchar(255) NOT NULL COMMENT '设备型号',
	`device_sn` varchar(255) NOT NULL COMMENT '设备序列号',
	`aid` int(11) DEFAULT NULL COMMENT '所属代理ID',
	`mid` int(11) DEFAULT NULL COMMENT '商户ID',
	`store_id` int(11) DEFAULT NULL COMMENT '门店ID',
	`info` varchar(255) DEFAULT NULL COMMENT '备注',
	`ad_year` varchar(50) DEFAULT NULL COMMENT '按年收费金额',
	`ad_month` varchar(50) DEFAULT NULL COMMENT '按月收费金额',
	`create_time` varchar(20) DEFAULT NULL COMMENT '创建时间',
	`update_time` varchar(20) DEFAULT NULL COMMENT '更新时间',
	`domain_auth` varchar(50) NOT NULL COMMENT '所属',
	PRIMARY KEY (`id`),
	INDEX `status` USING BTREE (`status`) comment '',
	INDEX `type` USING BTREE (`type`) comment '',
	INDEX `device_number` USING BTREE (`device_number`) comment '',
	INDEX `device_sn` USING BTREE (`device_sn`) comment '',
	INDEX `mid` USING BTREE (`mid`) comment '',
	INDEX `store_id` USING BTREE (`store_id`) comment '',
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=5 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_invite_befit_count` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`aid` int(11) NOT NULL,
	`code` varchar(10) NOT NULL,
	`name` varchar(100) DEFAULT NULL,
	`phone` varchar(15) DEFAULT NULL,
	`grade` tinyint(2) DEFAULT NULL,
	`grade_name` varchar(10) DEFAULT NULL,
	`zt_1` varchar(20) DEFAULT NULL,
	`zt_2` varchar(20) DEFAULT NULL,
	`zt_3` varchar(20) DEFAULT NULL,
	`zt_4` varchar(20) DEFAULT NULL,
	`jt_1` varchar(20) DEFAULT NULL,
	`jt_2` varchar(20) DEFAULT NULL,
	`jt_3` varchar(20) DEFAULT NULL,
	`jt_4` varchar(20) DEFAULT NULL,
	`total` decimal(10,2) DEFAULT NULL,
	`create_time` datetime DEFAULT NULL,
	`domain_auth` varchar(20) NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `aid` USING BTREE (`aid`) comment '',
	INDEX `code` USING BTREE (`code`) comment '',
	INDEX `total` USING BTREE (`total`) comment '',
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=3 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_invite_code` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`code` varchar(10) NOT NULL,
	`pid` int(11) DEFAULT NULL COMMENT '所属代理或系统',
	`create_time` varchar(25) NOT NULL,
	`status` tinyint(1) DEFAULT 1 COMMENT '状态 1启用 0禁用',
	`domain_auth` varchar(50) NOT NULL COMMENT '所属品牌',
	PRIMARY KEY (`id`),
	INDEX `code` USING BTREE (`code`) comment '',
	INDEX `pid` USING BTREE (`pid`) comment '',
	INDEX `status` USING BTREE (`status`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=691 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_invite_draw_list` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`aid` int(11) NOT NULL,
	`total` decimal(10,2) NOT NULL COMMENT '清算金额',
	`info` varchar(255) DEFAULT NULL,
	`create_time` varchar(30) NOT NULL COMMENT '清算时间',
	`domain_auth` varchar(50) NOT NULL,
	PRIMARY KEY (`id`)) ENGINE=`InnoDB` AUTO_INCREMENT=8 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='结算记录' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_invite_pay_order` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`aid` int(11) NOT NULL COMMENT '代理ID',
	`grade` tinyint(2) NOT NULL COMMENT '付费的等级',
	`total` decimal(10,2) NOT NULL COMMENT '支付金额',
	`type` varchar(5) NOT NULL DEFAULT '' COMMENT 'wx ali',
	`out_trade_no` varchar(50) NOT NULL COMMENT '订单号',
	`status` tinyint(1) DEFAULT 0 COMMENT '支付结果',
	`create_time` varchar(30) NOT NULL COMMENT '订单创建时间',
	`transaction_id` varchar(50) DEFAULT NULL COMMENT '官方订单号',
	`update_time` varchar(30) DEFAULT NULL COMMENT '更新时间',
	`openid` varchar(255) DEFAULT NULL COMMENT '支付者标识',
	`pay_mid` int(11) NOT NULL COMMENT '收单商户使用id',
	`domain_auth` varchar(20) NOT NULL COMMENT '系统标识',
	PRIMARY KEY (`id`),
	INDEX `aid` USING BTREE (`aid`) comment '',
	INDEX `out_trade_no` USING BTREE (`out_trade_no`) comment '',
	INDEX `total` USING BTREE (`total`) comment '',
	INDEX `status` USING BTREE (`status`) comment '',
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '',
	INDEX `grade` USING BTREE (`grade`) comment '',
	INDEX `transaction_id` USING BTREE (`transaction_id`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=20 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_invite_setting` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`data` text NOT NULL,
	`update_time` varchar(30) DEFAULT NULL COMMENT '更新时间',
	`domain_auth` varchar(30) NOT NULL COMMENT '所属',
	PRIMARY KEY (`id`),
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `wbs_mch_agent` ADD COLUMN `pay_status` tinyint(1) DEFAULT 0 COMMENT '是否付费开通' after `ad4`;
ALTER TABLE `wbs_mch_agent` ADD COLUMN `invite_code` varchar(10) CHARACTER SET utf8 DEFAULT '' COMMENT '所属邀请人推荐码' after `pay_status`;
ALTER TABLE `wbs_mch_agent` ADD COLUMN `grade` tinyint(2) DEFAULT NULL COMMENT '等级 1服务商 2省代 3市代 4区代' after `invite_code`;
ALTER TABLE `wbs_mch_alisms_config` ADD COLUMN `sms_member` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '会员卡验证码' after `sms_quick_pay`;
DROP TABLE `wbs_mch_industry_copy`;
CREATE TABLE `wbs_mch_member_activity` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`mid` int(11) NOT NULL COMMENT '所属商户',
	`type` varchar(100) NOT NULL COMMENT '活动类型  cz充值送 xf消费返 jh激活送 tj推荐送',
	`name` varchar(255) NOT NULL COMMENT '活动名称',
	`store_id` varchar(255) DEFAULT NULL COMMENT '所属门店',
	`data` text NOT NULL COMMENT '活动规则',
	`status` tinyint(1) DEFAULT NULL COMMENT '状态  1启用 0禁用',
	`create_time` varchar(50) DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY (`id`),
	INDEX `mid` USING BTREE (`mid`) comment '',
	INDEX `store_id` USING BTREE (`store_id`) comment '',
	INDEX `type` USING BTREE (`type`) comment '',
	INDEX `status` USING BTREE (`status`) comment '',
	INDEX `data` USING BTREE (`data`(255)) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=38 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_mch_member_order` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`out_trade_no` varchar(30) DEFAULT NULL COMMENT '交易号',
	`user_id` int(11) NOT NULL COMMENT '会员ID',
	`total` decimal(10,2) DEFAULT NULL COMMENT '交易金额',
	`sxf` varchar(255) DEFAULT NULL COMMENT '手续费',
	`money` decimal(10,2) DEFAULT NULL COMMENT '实收',
	`type` varchar(20) NOT NULL COMMENT '交易类型',
	`desc` varchar(100) DEFAULT NULL COMMENT '交易简述',
	`mid` int(11) DEFAULT NULL COMMENT '交易商户',
	`store_id` int(11) DEFAULT NULL COMMENT '交易门店',
	`total_type` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 增加 2 扣款',
	`pay_type` varchar(50) DEFAULT NULL COMMENT '消费或充值入口位置 wx 微信 ali 支付宝',
	`create_time` varchar(30) NOT NULL COMMENT '交易时间',
	`domain_auth` varchar(30) NOT NULL COMMENT '所属品牌',
	`status` tinyint(1) DEFAULT 1 COMMENT '状态 1有效 其它无效',
	`czr` varchar(255) DEFAULT NULL COMMENT ' 充值类型 操作人手机号',
	PRIMARY KEY (`id`)) ENGINE=`InnoDB` AUTO_INCREMENT=352 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_mch_member_temp` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`mid` int(11) NOT NULL COMMENT '所属商户',
	`name` varchar(20) NOT NULL COMMENT '会员卡名称',
	`xc` varchar(20) NOT NULL COMMENT '宣传语',
	`bg` varchar(20) DEFAULT NULL COMMENT '背景标识',
	`number` int(11) DEFAULT NULL COMMENT '数量',
	`phone` varchar(15) DEFAULT NULL COMMENT '联系电话',
	`help` varchar(255) DEFAULT NULL COMMENT '会员卡使用说明',
	`status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用 1启用 其它禁用',
	`domain_auth` varchar(50) NOT NULL COMMENT '品牌授权码',
	`pay_store` int(11) DEFAULT NULL COMMENT '充值门店ID',
	PRIMARY KEY (`id`),
	INDEX `mid` USING BTREE (`mid`) comment '',
	INDEX `status` USING BTREE (`status`) comment '',
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=5 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_mch_member_user` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`num` varchar(30) NOT NULL COMMENT '会员卡号',
	`st_num` varchar(30) DEFAULT NULL COMMENT '实体会员卡号',
	`mid` int(11) NOT NULL COMMENT '商户ID',
	`store_id` int(11) DEFAULT NULL COMMENT '门店ID',
	`phone` varchar(12) NOT NULL COMMENT '用户手机号',
	`name` varchar(20) DEFAULT NULL COMMENT '用户姓名',
	`birthday` varchar(10) DEFAULT NULL COMMENT '生日',
	`wx_id` varchar(255) DEFAULT NULL COMMENT '用户微信标识OPENID',
	`ali_id` varchar(50) DEFAULT NULL COMMENT '支付宝用户标识ID',
	`create_time` varchar(30) NOT NULL COMMENT '创建时间',
	`tjr` varchar(12) DEFAULT NULL COMMENT '推荐人手机号',
	`domain_auth` varchar(20) NOT NULL COMMENT '所属品牌',
	PRIMARY KEY (`id`),
	INDEX `wx_id` USING BTREE (`wx_id`) comment '',
	INDEX `mid` USING BTREE (`mid`) comment '',
	INDEX `ali_id` USING BTREE (`ali_id`) comment '',
	INDEX `store_id` USING BTREE (`store_id`) comment '',
	INDEX `phone` USING BTREE (`phone`) comment '',
	INDEX `num` USING BTREE (`num`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=25 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='用户会员信息表' CHECKSUM=0 DELAY_KEY_WRITE=0;
CREATE TABLE `wbs_notice_list` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`type` tinyint(2) NOT NULL COMMENT '公共类型',
	`title` varchar(30) NOT NULL COMMENT '公共标题',
	`info` varchar(255) NOT NULL COMMENT '公共内容',
	`uid` int(11) NOT NULL,
	`status` tinyint(1) DEFAULT NULL,
	`sort` int(11) DEFAULT NULL COMMENT '排序',
	`create_time` datetime NOT NULL,
	`domain_auth` varchar(30) NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `type` USING BTREE (`type`) comment '',
	INDEX `domain_auth` USING BTREE (`domain_auth`) comment '',
	INDEX `status` USING BTREE (`status`) comment '') ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;

DROP TABLE IF EXISTS `wbs_auth_rule`;
CREATE TABLE `wbs_auth_rule` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '父级id',
  `name` char(80) NOT NULL DEFAULT '' COMMENT '规则唯一标识',
  `title` char(20) NOT NULL DEFAULT '' COMMENT '规则中文名称',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态：为1正常，为0禁用',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `condition` char(100) NOT NULL DEFAULT '' COMMENT '规则表达式，为空表示存在就验证，不为空表示按照条件验证',
  `icon` varchar(50) NOT NULL COMMENT '菜单图标',
  `menu` tinyint(1) NOT NULL COMMENT '是否以菜单形式显示',
  `domain_auth` varchar(255) NOT NULL,
  `orders` int(11) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=319 DEFAULT CHARSET=utf8 COMMENT='规则表';

BEGIN;
INSERT INTO `wbs_auth_rule` VALUES ('16', '3', 'Admin/Rule/add_group', '添加角色', '1', '1', '', '', '0', '', null), ('17', '3', 'Admin/Rule/edit_group', '修改角色', '1', '1', '', '', '0', '', null), ('18', '3', 'Admin/Rule/delete_group', '删除角色', '1', '1', '', '', '0', '', null), ('20', '4', 'Admin/User/add_user', '添加用户', '1', '1', '', '', '0', '', null), ('1', '0', 'Admin/Index/index', '控制台', '1', '1', '', 'fa-dashboard', '1', '', '1000'), ('147', '146', 'Admin/Mcha/adds', '添加渠道', '1', '1', '', '', '0', '', null), ('4', '6', 'Admin/User/index', '用户管理', '1', '1', '', '', '1', '', null), ('173', '154', 'Admin/Merchant/Auditing', '商户审核', '1', '1', '', '', '1', '', '300'), ('6', '0', 'Admin/Rule', '权限控制', '1', '1', '', 'fa-universal-access', '1', '', '0'), ('3', '6', 'Admin/Rule/rule_group', '角色管理', '1', '1', '', '', '1', '', null), ('207', '155', 'Admin/Merchant/mch_alleys_data', '商户通道切换数据(获取)', '1', '1', '', '', '0', '', '0'), ('206', '173', 'Admin/Merchant/Auditing_save', '审核信息-商户信息编辑保存', '1', '1', '', '', '0', '', '0'), ('15', '3', 'Admin/Rule/rule_distribution', '角色分配权限', '1', '1', '', '', '0', '', null), ('21', '4', 'Admin/User/edit_user', '修改用户', '1', '1', '', '', '0', '', null), ('143', '1', 'Admin/User/my_center', '个人中心', '1', '1', '', 'cd', '0', '', null), ('154', '0', 'Admin/Merchant', '商户管理', '1', '1', '', 'fa-send-o', '1', '', '900'), ('155', '154', 'Admin/Merchant/index', '商户列表', '1', '1', '', '', '1', '', '200'), ('156', '0', 'Admin/Orders', '交易管理', '1', '1', '', 'fa-bar-chart', '1', '', '800'), ('157', '156', 'Admin/Orders/index', '订单流水', '1', '1', '', '', '1', '', '100'), ('158', '157', 'Admin/Orders/detail', '订单详情', '1', '1', '', '', '0', '', null), ('159', '157', 'Admin/Orders/updates', '订单更新状态', '1', '1', '', '', '0', '', null), ('174', '155', 'Admin/Merchant/detail', '商户详情', '1', '1', '', '', '0', '', null), ('175', '154', 'Admin/Merchant/Auth_Fee', '商户认证', '1', '1', '', '', '1', '', '0'), ('168', '143', 'Admin/User/editpass', '修改密码', '1', '1', '', '', '0', '', null), ('176', '0', 'Admin/Agent', '代理管理', '1', '1', '', 'fa-users', '1', '', '600'), ('177', '176', 'Admin/Agent/lists', '代理列表', '1', '1', '', '', '1', '', '500'), ('204', '179', 'Admin/Agent/benefit_detail', '分润明细', '1', '1', '', '', '0', '', '0'), ('179', '176', 'Admin/Agent/benefit_count', '分润汇总', '1', '1', '', '', '1', '', '400'), ('180', '0', 'Admin/Extends', '扩展模块', '1', '1', '', 'fa-qrcode', '1', '', '400'), ('181', '180', 'Admin/Extends/qrcode', '收款码管理', '1', '1', '', '', '1', '', '100'), ('182', '180', 'Admin/Extends/weixin_list', '公众号管理', '1', '1', '', '', '1', '', '50'), ('183', '0', 'Admin/Systems', '系统配置', '1', '1', '', 'fa-dribbble', '1', '', '200'), ('184', '183', 'Admin/Systems/index', '基础配置', '1', '1', '', '', '1', '', '200'), ('185', '183', 'Admin/Systems/pay_config', '支付配置', '1', '1', '', '', '1', '', null), ('186', '183', 'Admin/Systems/sms_config', '短信配置', '1', '1', '', '', '1', '', null), ('205', '173', 'Admin/Merchant/Auditing_status', '审核处理结果', '1', '1', '', '', '0', '', '0'), ('188', '177', 'Admin/Agent/adds', '添加代理', '1', '1', '', '', '0', '', '0'), ('189', '177', 'Admin/Agent/detail', '代理详情', '1', '1', '', '', '0', '', '0'), ('190', '177', 'Admin/Agent/edits', '编辑代理信息', '1', '1', '', '', '0', '', '0'), ('191', '181', 'Admin/Extends/adds', '生成收款码', '1', '1', '', '', '0', '', '0'), ('192', '173', 'Admin/Merchant/Auditing_detail', '审核信息', '1', '1', '', '', '0', '', '0'), ('193', '155', 'Admin/Merchant/api_way', '支付通道配置', '1', '1', '', '', '0', '', '0'), ('194', '155', 'Admin/Merchant/store', '门店列表', '1', '1', '', '', '0', '', '0'), ('195', '155', 'Admin/Merchant/mdata', '进件-商户详情', '1', '1', '', '', '0', '', '0'), ('196', '155', 'Admin/Merchant/mdata_edit', '进件-编辑商户信息', '1', '1', '', '', '0', '', '0'), ('197', '177', 'Admin/Agent/A_Rate', '代理费率配置', '1', '1', '', '', '0', '', '0'), ('198', '155', 'Admin/Merchant/store_config', '门店配置(打印机)', '1', '1', '', '', '0', '', '0'), ('199', '155', 'Admin/Merchant/store_data', '门店信息编辑', '1', '1', '', '', '0', '', '0'), ('200', '155', 'Admin/Merchant/store_set', '门店新增(添加)', '1', '1', '', '', '0', '', '0'), ('201', '155', 'Admin/Merchant/bind_codes', '门店绑定收款码ID', '1', '1', '', '', '0', '', '0'), ('202', '155', 'Admin/Merchant/store_user', '门店店员管理', '1', '1', '', '', '0', '', '0'), ('203', '173', 'Admin/Merchant/Auditing_edits', '审核-商户信息编辑', '1', '1', '', '', '0', '', '0'), ('208', '155', 'Admin/Merchant/mch_alleys_saves', '商户通道切换数据(保存)', '1', '1', '', '', '0', '', '0'), ('209', '155', 'Admin/Merchant/print_save', '门店配置(打印机)信息更新', '1', '1', '', '', '0', '', '0'), ('210', '155', 'Admin/Merchant/store_user_data', '门店店员编辑(数据获取)', '1', '1', '', '', '0', '', '0'), ('211', '155', 'Admin/Merchant/store_user_del', '门店店员删除', '1', '1', '', '', '0', '', '0'), ('212', '155', 'Admin/Merchant/store_user_save', '门店店员编辑(数据保存)', '1', '1', '', '', '0', '', '0'), ('213', '176', 'Admin/Agent/dialog_data', '代理扩展', '1', '1', '', '', '0', '', '0'), ('214', '213', 'Admin/Agent/dialog', '代理数据检索', '1', '1', '', '', '0', '', '0'), ('215', '154', 'Admin/Merchant/mch_dialog_data', '商户扩展', '1', '1', '', '', '0', '', '0'), ('216', '215', 'Admin/Merchant/mch_dialog', '商户信息检索', '1', '1', '', '', '0', '', '0'), ('217', '177', 'Admin/Agent/A_rata_save', '代理费率配置更新', '1', '1', '', '', '0', '', '0'), ('218', '181', 'Admin/Extends/codesdown', '收款码数据导出', '1', '1', '', '', '0', '', '0'), ('219', '182', 'Admin/Extends/weixin_adds', '公众号添加', '1', '1', '', '', '0', '', '0'), ('220', '182', 'Admin/Extends/detail', '公众号数据获取', '1', '1', '', '', '0', '', '0'), ('222', '155', 'Admin/Merchant/mdata_save', '进件-编辑商户信息更新保存', '1', '1', '', '', '0', '', '0'), ('223', '155', 'Admin/Merchant/alleys_in', '商户进件(进件银行)', '1', '1', '', '', '0', '', '0'), ('224', '176', 'Admin/Agent/performance', '业绩分析', '0', '1', '', '', '0', '', '100'), ('225', '181', 'Admin/Extends/allot_agent', '收款码分配更换代理', '1', '1', '', '', '0', '', '0'), ('228', '215', 'Admin/Merchant/transfer_agent', '商户过户(更换)代理', '1', '1', '', '', '0', '', '0'), ('229', '215', 'Admin/Merchant/mch_sms', '审核商户通过短信通知', '1', '1', '', '', '0', '', '0'), ('231', '154', 'Admin/Merchant/alter_log', '变更记录', '1', '1', '', '', '1', '', '0'), ('232', '231', 'Admin/Merchant/alter_log_data', '变更详细信息/费率', '1', '1', '', '', '0', '', '0'), ('233', '155', 'Admin/Merchant/alter', '通道-商户信息费率变更', '1', '1', '', '', '0', '', '0'), ('234', '181', 'Admin/Merchant/abook', '手动录入商户', '1', '1', '', '', '0', '', '0'), ('235', '181', 'Admin/Merchant/abook_save', '录入商户数据保存', '1', '1', '', '', '0', '', '0'), ('236', '173', 'Admin/Merchant/codes_reload', '收款码回收', '1', '1', '', '', '0', '', '0'), ('237', '179', 'Admin/Agent/benefit_status', '分润结算状态操作', '1', '1', '', '', '0', '', '0'), ('238', '215', 'Admin/Merchant/store_dialog', '门店信息检索', '1', '1', '', '', '0', '', '0'), ('239', '0', 'Admin/Partner', '渠道信息', '1', '1', '', 'fa-codepen', '1', '', '0'), ('240', '239', 'Admin/Partner/benefit_count', '分润信息', '1', '1', '', '', '1', '', '0'), ('241', '240', 'Admin/Partner/benefit_detail', '分润明细', '1', '1', '', '', '0', '', '0'), ('242', '155', 'Admin/Merchant/mch_status', '商户状态退回(未审核状态)', '1', '1', '', '', '0', '', '0'), ('243', '155', 'Admin/Merchant/mch_detail', '商户基本信息', '1', '1', '', '', '0', '', '0'), ('244', '155', 'Admin/Merchant/alleys_updata', '商户更新进件(驳回重新提交)', '1', '1', '', '', '0', '', '0'), ('245', '155', 'Admin/Merchant/card_api_way', '无卡快捷-通道配置', '1', '1', '', '', '0', '', '0'), ('246', '155', 'Admin/Merchant/card_api_way_status', '无卡快捷-通道状态开关', '1', '1', '', '', '0', '', '0'), ('247', '155', 'Admin/Merchant/card_alleys_in', '无卡快捷-通道商户进件', '1', '1', '', '', '0', '', '0'), ('248', '155', 'Admin/Merchant/card_alter', '无卡快捷-商户费率结算信息变更', '1', '1', '', '', '0', '', '0'), ('249', '155', 'Admin/Merchant/card_mdata', '无卡快捷-商户信息详情', '1', '1', '', '', '0', '', '0'), ('250', '155', 'Admin/Merchant/card_mdata_edit', '无卡快捷-商户信息编辑', '1', '1', '', '', '0', '', '0'), ('251', '155', 'Admin/Merchant/card_mdata_save', '无卡快捷-商户信息编辑保存', '1', '1', '', '', '0', '', '0'), ('252', '154', 'Admin/Merchant/card_validate_log', '鉴权记录', '1', '1', '', '', '1', '', '0'), ('253', '180', 'Admin/Extends/AdData', '广告位管理', '1', '1', '', '', '1', '', '0'), ('254', '1', 'Admin/Message/index', '消息列表', '1', '1', '', '', '0', '', '0'), ('255', '254', 'Admin/Message/detail', '消息详情', '1', '1', '', '', '0', '', '0'), ('256', '253', 'Admin/Extends/AdDataAdd', '新增广告', '1', '1', '', '', '0', '', '0'), ('257', '156', 'Admin/Orders/TxLog', '提现记录(V通道)', '1', '1', '', '', '0', '', '0'), ('258', '185', 'Admin/Systems/add_template', '一键增加模板消息', '1', '1', '', '', '1', '', '0'), ('259', '215', 'Admin/Merchant/SendAuthTemplate', '发送商户未认证模板消息提醒', '1', '1', '', '', '1', '', '0'), ('260', '0', 'Admin/WeiXin/index', '微信公众号-功能', '1', '1', '', '', '0', '', '0'), ('261', '260', 'Admin/WeiXin/MenuList', '自定义菜单', '1', '1', '', 'fa-wechat', '1', '', '0'), ('263', '260', 'Admin/WeiXin/Material', '图文素材管理', '1', '1', '', 'fa-folder-o', '1', '', '0'), ('264', '263', 'Admin/WeiXin/Material_news', '新增图文', '1', '1', '', '', '0', '', '0'), ('266', '263', 'Admin/WeiXin/MaterialImage', '图片管理', '1', '1', '', '', '0', '', '0'), ('267', '260', 'Admin/WeiXin', '自动回复', '1', '1', '', 'fa-recycle', '1', '', '100'), ('268', '267', 'Admin/WeiXin/KeyReply', '关键词回复', '1', '1', '', '', '1', '', '0'), ('269', '267', 'Admin/WeiXin/BeadReply', '被关注回复', '1', '1', '', '', '1', '', '0'), ('270', '267', 'Admin/WeiXin/AutoReply', '无应答回复', '1', '1', '', '', '1', '', '0'), ('271', '155', 'Admin/Merchant/terminal', '终端管理', '1', '1', '', '', '0', '', '0'), ('272', '155', 'Admin/Merchant/terminal_add', '终端添加/编辑', '1', '1', '', '', '0', '', '0'), ('273', '155', 'Admin/Merchant/terminal_status', '终端状态更新', '1', '1', '', '', '0', '', '0'), ('274', '0', 'Admin/Extension', '营销推广', '1', '1', '', 'fa-paw', '0', '', '890'), ('275', '274', 'Admin/Extension/grade', '等级配置', '1', '1', '', '', '1', '', '0'), ('276', '274', 'Admin/Extension/setting', '基础设置', '1', '1', '', '', '1', '', '0'), ('277', '274', 'Admin/Extension/gradeSet', '添加/编辑等级', '1', '1', '', '', '0', '', '0'), ('278', '274', 'Admin/Extension/Invite', '推广列表', '1', '1', '', '', '1', '', '0'), ('279', '274', 'Admin/Extension/benefit', '推广分润', '1', '1', '', '', '1', '', '0'), ('280', '279', 'Admin/Extension/benefitDetail', '分润详情', '1', '1', '', '', '0', '', '0'), ('281', '274', 'Admin/Extension/alterGradeLog', '等级日志', '1', '1', '', '', '1', '', '0'), ('282', '274', 'Admin/Extension/tools', '辅助工具', '1', '1', '', '', '1', '', '0'), ('283', '155', 'Admin/Merchant/flow', '流量配置', '1', '1', '', '', '0', '', '0'), ('284', '215', 'Admin/Flow/index', '流量管理', '1', '1', '', '', '0', '', '0'), ('285', '183', 'Admin/Flow/configs', '流量配置', '1', '1', '', '', '0', '', '0'), ('286', '215', 'Admin/Flow/setList', '流量充值记录', '1', '1', '', '', '0', '', '0'), ('287', '215', 'Admin/Flow/payList', '流量扣费记录', '1', '1', '', '', '0', '', '0'), ('288', '215', 'Admin/Flow/payPoll', '轮询配置', '1', '1', '', '', '0', '', '0'), ('289', '0', 'Admin/WxPay', '官方服务商', '1', '1', '', 'fa-code', '1', '', '900'), ('290', '289', 'Admin/WxPay/xwList', '小微入网', '1', '1', '', '', '1', '', '0'), ('291', '289', 'Admin/Isv/shopList', '支付宝口碑', '1', '1', '', '', '1', '', '0'), ('292', '291', 'Admin/Isv/shopCreate', '口碑入网', '1', '1', '', '', '0', '', '0'), ('293', '290', 'Admin/WxPay/xwIn', '进件', '1', '1', '', '', '0', '', '0'), ('294', '290', 'Admin/WxPay/info', '资料', '1', '1', '', '', '0', '', '0'), ('295', '290', 'Admin/WxPay/mchConfig', '配置', '1', '1', '', '', '0', '', '0'), ('296', '290', 'Admin/WxPay/alterInfo', '变更', '1', '1', '', '', '0', '', '0'), ('297', '180', 'Admin/Extends/wxQwAdData', '微信青蛙广告', '1', '1', '', '', '1', '', '0'), ('298', '297', 'Admin/Extends/wxQwAdDataSet', '添加广告', '1', '1', '', '', '0', '', '0'), ('299', '155', 'Admin/Merchant/setAlleyRate', '通道费率更新', '1', '1', '', '', '0', '', '0'), ('300', '290', 'Admin/WxPay/upInfoCreate', '小微升级', '1', '1', '', '', '0', '', '0'), ('301', '290', 'Admin/WxPay/upInfo', '升级记录', '1', '1', '', '', '0', '', '0'), ('302', '156', 'Admin/Orders/statistics', '汇总统计', '1', '1', '', '', '1', '', '0'), ('303', '0', 'Admin/Invite', '推荐码管理', '1', '1', '', 'fa-share-alt', '0', '', '0'), ('304', '0', 'Admin/Face', '刷脸设备管理', '1', '1', '', 'fa-television', '1', '', '0'), ('305', '303', 'Admin/Invite/lists', '推荐码列表', '1', '1', '', '', '1', '', '0'), ('306', '303', 'Admin/Invite/setting', '推荐码设置', '1', '1', '', '', '1', '', '0'), ('307', '303', 'Admin/Invite/regList', '推荐码注册汇总', '1', '1', '', '', '1', '', '0'), ('308', '304', 'Admin/Face/lists', '设备列表', '1', '1', '', '', '1', '', '0'), ('309', '304', 'Admin/Face/deviceReward', '设备奖励', '1', '1', '', '', '1', '', '0'), ('310', '308', 'Admin/Face/adds', '添加设备', '1', '1', '', '', '0', '', '0'), ('311', '308', 'Admin/Face/edits', '编辑设备', '1', '1', '', '', '0', '', '0'), ('312', '308', 'Admin/Face/deviceStatus', '设备状态', '1', '1', '', '', '0', '', '0'), ('313', '305', 'Admin/Invite/regDetailList', '注册明细', '1', '1', '', '', '0', '', '0'), ('314', '307', 'Admin/Invite/inviteDrawList', '分润结算记录', '1', '1', '', '', '0', '', '0'), ('315', '307', 'Admin/Invite/drawSet', '增加结算记录', '1', '1', '', '', '0', '', '0'), ('316', '0', 'Admin/Notice/lists', '公告管理', '1', '1', '', 'fa-volume-up', '1', '', '0'), ('317', '183', 'Admin/Systems/bank_list', '银行管理', '1', '1', '', '', '0', '', '0'), ('318', '183', 'Admin/Systems/link_bank_list', '联行号管理', '1', '1', '', '', '0', '', '0');
COMMIT;


